version: '3.9'

services:
  haproxy:
    container_name: haproxy
    hostname: haproxy.dev
    build: 
      context: ./files/haproxy
      dockerfile: Dockerfile
    volumes:
      - ./files/haproxy/confs:/usr/local/etc/haproxy:rw
    ports:
      - "80:80"
      - "1936:1936"
    networks:
      - frontend
    restart: always
  syslog:
    container_name: logging
    hostname: logging.dev
    build:
      context: ./files/logging
      dockerfile: Dockerfile
    volumes:
      - logging:/sidecar
    networks:
      - backend
      - frontend
  app1:
    build: 
      context: ./files/app
      dockerfile: Dockerfile
    volumes:
      - ./files/app:/app:rw
    container_name: app1
    hostname: app1.dev
    ports:
      - "8001:5000"
    networks:
      - backend
      - frontend
    depends_on:
      - haproxy
  app2:
    build: 
      context: ./files/app
      dockerfile: Dockerfile
    volumes:
      - ./files/app:/app:rw
    container_name: app2
    hostname: app2.dev
    ports:
      - "8002:5000"
    networks:
      - backend
      - frontend
    depends_on:
      - haproxy

networks:
  frontend:
  backend:
volumes:
  logging:
