version: '3.9'

services:
  haproxy:
    container_name: haproxy
    hostname: haproxy.dev
    build: 
      context: ./files/haproxy
      dockerfile: Dockerfile
    volumes:
      - ./files/haproxy/confs:/usr/local/etc/haproxy:rw
    ports:
      - "80:80"
      - "1936:1936"
    links:
      - "app1"
      - "app2"
      - "app3"
    networks:
      - frontend
    restart: always
  app1:
    build: 
      context: ./files/app
      dockerfile: Dockerfile
    volumes:
      - ./files/app:/app:rw
    container_name: app1
    #hostname: app.dev
    ports:
      - "5000"
    networks:
      - backend
      - frontend

  app2:
    build: 
      context: ./files/app
      dockerfile: Dockerfile
    volumes:
      - ./files/app:/app:rw
    container_name: app2
    #hostname: app.dev
    ports:
      - "5000"
    networks:
      - backend
      - frontend

  app3:
    build: 
      context: ./files/app
      dockerfile: Dockerfile
    volumes:
      - ./files/app:/app:rw
    container_name: app3
    #hostname: app.dev
    ports:
      - "5000"
    networks:
      - backend
      - frontend

networks:
  frontend:
  backend:
